name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # 12시간마다 자동 실행
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_days: 14
          config_timezone: Asia/Seoul
          config_twemoji: yes
          filename: Metrics.svg
